public class Main {
public static void main(String[] args) {    
  
  // winter, spring, summer, autumn
  // warm jacket, t-shirt, swimming suite, rain coat
  
  double temp = 5.6;

  if (temp <= 5) {
    System.out.println("Wear a super warm jacket!");
  } 
  else if (temp <= 15) {
    System.out.println("Wear a warm jacket!");
  } 
  else if (temp <= 30) {
    System.out.println("Wear a t-shirt!");
  } 
  else {
    System.out.println("Don't wear anything!");
  }
  
}

}
